### ISSUE TITLE
Error: endpoints to REST-API

### ISSUE THREAD

**Issue by christianheimann** [hrz-unimr/Ilias.RESTPlugin#23]
Hi everyone, hi Thomas,

After the last pull we did friday, I was not able to reach the Admin-Panel of the RestPlugin. The following error was displayed: 

Could not locate/contact the REST-API endpoint(s) at:
http://localhost:8888/ [POST information]
http://localhost:8888//ILIASrestplugin.php [File URL]
http://localhost:8888//ILIAS [Subdomain URL]

The Admin-Panel requires an active REST-Endpoint to work.

May somebody help in that issue resp. fix it? Thanks for any suggestions.

**Comment by disc5** [comment]
Hi Christian,

thanks for the issue report. The issue should be resolved by now, please try: https://github.com/hrz-unimr/Ilias.RESTPlugin/releases/tag/v1.4.1.

Reasons:
1) Failed automatic login to the Admin-Panel: "bridge" not activated for the primary apollo API-Key. Bridge: enables to exchange an ILIAS Session for an OAuth2-Token (and vice-versa).
2) Missing permissions for the primary API-Key to use /v1/clients routes.

Cheers,
Dirk

**Comment by christianheimann** [comment]
Thank you very much for the immediate response!

… I pulled the v1.4.1, but sorry, the same error is still displayed.

**Comment by disc5** [comment]
We try to avoid it, but unfortunately it is not possible this time to make an update directly from a former version to the current version v1.4.1.  A reset of the plugin is required as described in (https://github.com/hrz-unimr/Ilias.RESTPlugin/releases/tag/v1.4.1) due to the many database layout changes?

We you tried that ... can you check table ui_uihk_rest_perm (SELECT * FROM `ui_uihk_rest_perm`)? There should be entries like /v1/clients GET, ....

Which OS and ILIAS version are you using?

**Comment by disc5** [comment]
I found another source that leads to the above mentioned error: if the log path is not set correctly,i.e. does not exist or is writable, then the error shows up. 

Please bug fix the following:
File: REST/RESTConroller/app.php
Set variable $restLog accordingly.
